version: 2.1

orbs:
  heroku: circleci/heroku@1.1.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - heroku/install
      - run: ./script.sh

workflows:
  version: 2.1
  default-ci-workflow:
    jobs:
      - build
